version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:80'
    # volumes:
    #   - .:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=df56d689878bd6a2a408421655881d5b
      - DATABASE_URL="mariadb://root:root@127.0.0.1:3306/mapa_academico?serverVersion=mariadb-10.4.22&charset=utf8mb4"
    networks:
      - app-network

  database:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mapa_academico
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
     - '3306:3306'
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - app-network
    links:
      - database:database

networks:
  app-network: