version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mapa_academico
    ports:
      - '8081:80'
    depends_on:
      - database
    env_file:
      - ./.env 
    networks:
      - app-network

  database:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mapa_academico
    ports:
     - '3306:3306'
    networks:
      - app-network
    volumes:
      - ./doc/db/:/docker-entrypoint-initdb.d/:ro
  
  phpmyadmin:
    image: phpmyadmin:5.1.1
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    networks:
      - app-network
    links:
      - database:database

  app-migrations:
    image: mapa_academico
    depends_on:
      - app 
    env_file:
      - ./.env
    volumes:
      - ./bin/exec_migrations.sh:/tmp/exec_migrations.sh
    command: ["sh", "/tmp/exec_migrations.sh"]
    networks:
      - app-network

networks:
  app-network:
